/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/signUp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutCardNewRouteImport } from './routes/_layout/card.new'
import { Route as LayoutCardIdRouteImport } from './routes/_layout/card.$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCardNewRoute = LayoutCardNewRouteImport.update({
  id: '/card/new',
  path: '/card/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCardIdRoute = LayoutCardIdRouteImport.update({
  id: '/card/$id',
  path: '/card/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/signUp': typeof SignUpRoute
  '/card/$id': typeof LayoutCardIdRoute
  '/card/new': typeof LayoutCardNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signUp': typeof SignUpRoute
  '/': typeof LayoutIndexRoute
  '/card/$id': typeof LayoutCardIdRoute
  '/card/new': typeof LayoutCardNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signUp': typeof SignUpRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/card/$id': typeof LayoutCardIdRoute
  '/_layout/card/new': typeof LayoutCardNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signUp' | '/card/$id' | '/card/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/signUp' | '/' | '/card/$id' | '/card/new'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/signUp'
    | '/_layout/'
    | '/_layout/card/$id'
    | '/_layout/card/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signUp': {
      id: '/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/card/new': {
      id: '/_layout/card/new'
      path: '/card/new'
      fullPath: '/card/new'
      preLoaderRoute: typeof LayoutCardNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/card/$id': {
      id: '/_layout/card/$id'
      path: '/card/$id'
      fullPath: '/card/$id'
      preLoaderRoute: typeof LayoutCardIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCardIdRoute: typeof LayoutCardIdRoute
  LayoutCardNewRoute: typeof LayoutCardNewRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCardIdRoute: LayoutCardIdRoute,
  LayoutCardNewRoute: LayoutCardNewRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
