/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/v1/auth/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Регистрация
		 * @description Регистрация нового пользователя
		 */
		post: operations["register_api_v1_auth_register_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Авторизация через почту и пароль
		 * @description Получить JWT access и refresh токены
		 */
		post: operations["login_access_token_api_v1_auth_login_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/refresh": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Обновление токена
		 * @description Обновить JWT access и refresh токен
		 */
		post: operations["refresh_api_v1_auth_refresh_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Выход из профиля
		 * @description Отзыв refresh токена
		 */
		delete: operations["logout_api_v1_auth_logout_delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Тест JWT access токена */
		get: operations["test_token_api_v1_auth_me_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/cards/all": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Все карточки пользователя
		 * @description Получение всех карточек пользователя
		 */
		get: operations["all_cards_api_v1_cards_all_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/cards/create": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Создать карточки
		 * @description Создание новых карточек на основе полученного файла
		 */
		post: operations["create_card_api_v1_cards_create_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/cards/{card_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Получить карточку по id
		 * @description Получение карточки по id
		 */
		get: operations["get_card_api_v1_cards__card_id__get"];
		put?: never;
		post?: never;
		/**
		 * Удалить карточку
		 * @description Удаление карточки пользователя по id
		 */
		delete: operations["delete_api_v1_cards__card_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** Body_create_card_api_v1_cards_create_post */
		Body_create_card_api_v1_cards_create_post: {
			/**
			 * File
			 * Format: binary
			 */
			file: string;
		};
		/** Body_login_access_token_api_v1_auth_login_post */
		Body_login_access_token_api_v1_auth_login_post: {
			/** Grant Type */
			grant_type?: string | null;
			/** Username */
			username: string;
			/**
			 * Password
			 * Format: password
			 */
			password: string;
			/**
			 * Scope
			 * @default
			 */
			scope: string;
			/** Client Id */
			client_id?: string | null;
			/**
			 * Client Secret
			 * Format: password
			 */
			client_secret?: string | null;
		};
		/** Card */
		Card: {
			/**
			 * Id
			 * Format: uuid
			 */
			id?: string;
			/** Title */
			title: string;
			/** Content */
			content: {
				[key: string]: {
					question: string;
					answer: string;
				};
			};
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at?: string;
			/**
			 * User Id
			 * Format: uuid
			 */
			user_id: string;
			/** Content Len */
			content_len: number;
		};
		/** CardContainerList */
		CardContainerList: {
			/** Cards */
			cards: components["schemas"]["CardPublic"][];
			/** Count */
			count: number;
		};
		/** CardPublic */
		CardPublic: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Title */
			title: string;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/** Content */
			content: {
				[key: string]: {
					question: string;
					answer: string;
				};
			};
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components["schemas"]["ValidationError"][];
		};
		/** Token */
		Token: {
			/** Access Token */
			access_token: string;
			/**
			 * Token Type
			 * @default bearer
			 */
			token_type: string;
		};
		/** UserCreate */
		UserCreate: {
			/**
			 * Email
			 * Format: email
			 */
			email: string;
			/** Password */
			password: string;
			/** Full Name */
			full_name?: string | null;
		};
		/** UserPublic */
		UserPublic: {
			/**
			 * Email
			 * Format: email
			 */
			email: string;
			/** Full Name */
			full_name: string | null;
			/** Role */
			role: string;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	register_api_v1_auth_register_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UserCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserPublic"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	login_access_token_api_v1_auth_login_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/x-www-form-urlencoded": components["schemas"]["Body_login_access_token_api_v1_auth_login_post"];
			};
		};
		responses: {
			/** @description Успешная авторизация */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Token"];
				};
			};
			/** @description Неверный email или пароль */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Пользователь с указанным email не найден */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	refresh_api_v1_auth_refresh_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Токены успешно обновлены */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Token"];
				};
			};
			/** @description Токен уже был отозван/Токен истёк */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Такого токена не существует */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	logout_api_v1_auth_logout_delete: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Token"];
				};
			};
		};
	};
	test_token_api_v1_auth_me_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserPublic"];
				};
			};
		};
	};
	all_cards_api_v1_cards_all_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CardContainerList"];
				};
			};
		};
	};
	create_card_api_v1_cards_create_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"multipart/form-data": components["schemas"]["Body_create_card_api_v1_cards_create_post"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Card"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_card_api_v1_cards__card_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				card_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CardPublic"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_api_v1_cards__card_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				card_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CardPublic"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
}
